# Using a Merge queue makes Mergify automatically keep the PR
# up-to-date with 'main', one PR at a time.
queue_rules:
  - name: default_queue
    conditions:
      - label != bug
    merge_method: squash
    commit_message_template: |-
      This is my commit message template with co-author information:
      {% for co_author in co_authors | unique %}
      Co-Authored-By: {{ co_author.name }} <{{ co_author.email }}>
      {% endfor %}
      but probably this will be empty because I can't generate co-authors
      myself.
      At least, the author is {{ author }}

pull_request_rules:
  - name: Automatic squash merge on approval
    conditions:
      - label != bug

    actions:
      comment:
        message: Thank you for contributing! Your pull request is now going on the merge train (choo choo! Do not click update from main anymore, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      queue:
        name: default_queue
